const chemistry = {
    chapter1: `
    Concept of Chemistry Science is a branch called Natural Science. Over the ages, through observation or experimentation, 
    understanding or explaining any natural topic or predicting about it is the work of natural science. 
    Chemistry is a branch of natural science where the structure of matter, properties of matter, 
    and changes in matter are discussed. For example: Banana is a substance, inside the banana there 
    is carbon. Here, how the carbon atoms are inside the banana and how they work combined with all 
    other elements of the banana—this is what chemistry discusses, focusing on carbon and so on. Whether 
    it's matter or life or anything else, everything is a subject of discussion in chemistry. Natural 
    science has branches like Physics, Chemistry, Botany, Zoology, Microbiology, Astronomy, Soil Science, etc. 
    The metal coin you use is a gift of chemistry. There is a beautiful history about when, where, 
    and how chemistry expanded in human history. For example, it can be said that at one time we had to 
    make objects like stones and clay pots. People of that era started making whatever they could with 
    what was at hand. But they didn't have to follow the exact rules of science like now. From ancient Egypt, 
    chemistry has progressed towards complexity and change over time, and knowledge of chemistry has helped 
    people deeply to create new things. A lot has changed with time. At one time, humanity began to learn how 
    to alloy metals and transform them into metals. He named it Atom (meaning indivisible). Around the same time,
     some Indian philosophers expressed almost the same idea as Democritus. But those ideas had no experimental
      basis. Aristotle opposed this idea. Then philosophers like Aristotle thought that all matter is made of 
      earth, fire, water, and air. As a result, people did not accept it until a few days in the eighteenth 
      century. Arab Muslim philosophers tried to make gold from metals like copper, tin, lead. They also 
      tried to make a substance that, if eaten, would increase a person's age a lot or cure all diseases 
      and weaknesses. Many of them were the worst activities in chemistry. As a result, since they did not 
      get reality, they made many substances according to the model of making gold with various substances
       and left those experiments written. Basically, this was the first physics of chemistry's history. 
       Among the research phases of chemistry, the practice of chemistry was called Alchemy and in it the 
       first Alchemist of chemistry. In alchemy came another type of knowledge-research phase. The Greek 
       word alchemy came from the Arabic word kinmi. From kinmi came the word Chemi, which was used in 
       ancient times. In the nineteenth century, the first modern chemistry educator reviewed various 
       characteristics of chemistry to understand their research, which naturally gave us in our time. 
       Slowly, all the people who could do the right work, from the scientific perspective among the 
       scientists, they were doing better work. For this, they started providing more knowledge to 
       scientists. From that time, people became more thoughtful towards science and technology. 
       In the eighteenth century in Europe, many more scientists in chemistry, physics, Robert Boyle, 
       Sir Francis Bacon, John Dalton, Henry Cavendish and more individuals through modern science and
        more technologists through chemistry and other scientific subjects were conceived through 
        experimental means. Raw mango has various types of oil acids like: citric acid, malic acid, 
        etc. present, so raw mango is sour. But when the mango ripens, chemical changes occur in 
        these acids creating natural and fructose. So ripe mango is sweet. Kerosene, natural gas, 
        wax—these have main component hydrocarbon. Hydrocarbon is a compound of carbon and hydrogen. So when these burn, they react with oxygen in the air and create carbon dioxide, water, light, and heat. When excess hydrochloric acid accumulates in the stomach, there is acidity problem in the stomach. Antacid is two compounds aluminum hydroxide and magnesium hydroxide that neutralize acid. Where there is matter, there is chemistry. There are various gaseous substances in the atmosphere. Some chemical changes are ongoing in the atmosphere. For example, it can be said that oxygen in the air is undergoing oxidation change every moment. Not only the atmosphere, this change also happens at the bottom of the ocean. When life first happened on Earth, the Earth was not like this, the Earth was surrounded by gaseous elements. At that time there was no air. So there was no existence of life. Over billions of years, countless chemical changes have occurred. Atmosphere was created, water was created, thousands of kinds of substances were created, all these together presented the possibility for the living world on Earth. Various animals and plants of humans, from small microorganisms (like bacteria, algae, etc.) to large plants or animals, all are made with various kinds of chemical substances. Each body is a big chemical factory. Here, countless chemical reactions are happening every moment. And that's why we are alive. Again, with the progress of civilization, humans have created many substances by causing chemical reactions among various substances that are special materials for our use. Like fuel or after fuel, from this polished teeth, or covered skin with painted or used cosmetics which is the contribution of the factory. In this way, we have soap, toothpaste cream near the environment, this life related various kinds of materials to meet our needs in the field of fruit using fertilizer and pesticide for human use, diesel-and education transmission various substances that are being benefited by causing chemical reactions. It can be said that it will not go where the environment is familiar or in a small scope. 1.02 With the help of the table, some necessary fields of chemistry are given examples: Air, mainly oxygen, the air we take when we breathe, that air's oxygen reacts with food production inside the body to produce energy.
    Drinking water, various mineral salts with water, water participates in various chemical reactions in our body. It also works as a solvent for various substances in the body. Most of the body is water. Dissolved in various substances and nutrients in the body, it flows out of the body with the help of sweat. Besides water in drinking water, there are various types of mineral salts like-calcium, magnesium etc. metal salts, which are especially beneficial for our body.
    Fertilizer, calcium, magnesium, potassium, nitrogen, oxygen, carbon, phosphorus, essential elements for plants. Paper, cellulose, the invention of paper is a unique contribution to human civilization. Plants like bamboo, sugarcane mostly have polymer cellulose. In paper factories, paper is made through various kinds of chemical reactions from all these. Science has various branches. Like- chemistry, biology, physics, mathematics, environmental science, geology etc. There is a deep relationship between one branch of science and another branch. Other branches of science are dependent on chemistry, chemistry is also dependent on other branches. Below, the relationship of chemistry with various branches of science is explained with the help of a few examples:
    Relationship of chemistry with biology:
    Plants produce their living parts through photosynthesis process. Photosynthesis is basically a chemical reaction. Plants take carbon-dioxide and water from the air. With the help of protoplasm of sun's part present in green protection, this water and carbon dioxide react to produce necessary sugar or mineral. It produces protein, amino acid by eating various types of food in the body. Time creates chemical substances of the living world. All chemical substances of plant and animal world and various chemical reactions happening among them are discussed in biology. So biology and chemistry are interrelated.
    Relationship of chemistry with physics:
    Among the topics of physics are snow, electricity, various metallurgy etc. The heat used for electricity is the contribution of chemistry. Oil, gas which runs towards the production of energy for many men. Electricity production is dependent on physics. Heat from chemistry is a branch of chemistry whose various theories are basically established based on various theories of physics and era.
    Relationship of chemistry with mathematics:
    Chemistry has a close relationship with mathematics. Various theories and calculations of chemistry are done using mathematical formulas. Suppose, you woke up in the morning. After waking up, you brush your teeth with toothpaste. Then you sat down to read with books. During reading, mom gave you tea and biscuits. You drank tea. Went to eat. When going to bathe, you saw that your bathroom is a bit dirty. So you cleaned it with a little cleaner after getting up. During bathing, you used fragrant soap and shampoo. After bathing, you applied a little lotion on the body. Then for breakfast, you ate bread. Mom increased your liking with chocolate made bread paste. Notice, the things you are using like — paste, tea, biscuits, toilet cleaner, soap, shampoo, lotion or all those are contributions of chemistry.
    Not only that? Fertilizer has been made to make life fertile. Man has made insecticides so that insects do not destroy the yield in the field (insecticides) has made preservatives like chemical substances to preserve food for a long time i.e. we depend on chemistry for cultivation or food.
    Today, all the diseases like color, typhoid, smallpox etc. which are very common treatment for humans, at one time people died fighting such diseases. By acquiring knowledge of chemistry, man has discovered as a remedy for all these diseases. Such effects have been found worldwide in many special fields.
    Industry factories, vehicles, human use materials from natural environment chemical clothing have damaged our environment among them chemistry has done brother-fever-fever, skin mental health, sugar brother-fever-fever, various esbia, various kinds of khar (like— stone, lead, iron, cobalt etc.) with many more kinds of chemical use. This with air like atmosphere, with soil metha waterfit and other environment is causing damage. Today's various plants enter the body through and have various effects. We more from chemical effects spider.
    Our damage reason like— to damage food insects to make fertile because insecticide is used. But if used excessively, that thing insecticide washes in rain water male, nan-river, canal-bill water goes and pollutes that water. Again, mixes with air and pollutes air meaning excessive use of insecticide is harmful for the environment. If you study chemistry, you will be able to explain many such nature and real life things.
    So you have to understand that chemistry on one hand has invented many necessary and valuable things, similarly its neglect and inconsiderate use is causing severe damage to the environment. Here many big inventions have not happened. Again it is our duty to try to discover all those theories by doing chemistry research and research. So by studying your chemistry, on one hand you will be able to create many new things necessary for unemployment human welfare, at the same time you will understand how harmful it is for the environment. And your studying chemistry will take something more to the world. This is everyone's expectation from you.
    The goal of science is to do welfare for mankind. For this purpose, scientists are working tirelessly. When you hear the name scientist, Einstein, Newton, Aristotle, Galileo, Plato one great sage's name may come to mind, they are indeed great scientists. But scientist means they can be one scientist each of you. The coherent knowledge we acquire based on our experiments-observations is science. And trying to know something through this experiment is research. The one who does this research is the scientist.
    So if you acquire knowledge through some experiment, then you can be a scientist. The name of knowing something in the right method through experiment is research. Then you have understood that some specific methods have to be followed for research. There is substance for studying chemistry. Such all research methods are explained to you step by step.
    In the beginning phase of research, you have to determine what you want to know or what kind of new substance you want to discover. Suppose, you want to know what will be produced or solution will be if ammonium chloride is dissolved in water? This is called problem determination.Then you have to read some books on this subject first or collect such research papers from internetor elsewhere that such experiment has been done before and observe your result by hypothesizing from it. Suppose, from some book or research paper you know that heat is produced when capsicum anthanium is dissolved. From this research paper you will know before what evidence substances, what chemical substances and what method was used to dissolve capsicum anthanium. From that you will get idea about what evidence, chemical substances to use and what method to follow for your evidence substance (dissolving anthanium chloride in water). You may be encouraged to dissolve anthanium chloride in water as well. That is, you can hypothesize about the result.
    Again, you can decide about the necessary substances and in what method you will experiment. For example, suppose you will experiment how, when, anthanium chloride, thalimeter, work made clock, baljar (if) istalin things will be needed. First some amount of water has to be taken. Then water temperature has to be taken with thalimeter. Then collect the substances and properly add anthanium chloride some in water and dissolve properly with water rod. Every time see the water temperature with the help of thalimeter. This is evidence with which you will experiment. Now your experiment will start!
    You first take 250 ml water and see its temperature in thalimeter. Suppose, now temperature 25° C. If you keep with your baljar then mix 5 gram anthanium chloride with baljar's help some pour water. Pour cast pour dissolve anthanium chloride. As soon as dissolved, see temperature again with thalimeter. Suppose, this time temperature 20° C. Again if you experiment then capsicum chloride reaction 10 gram. Do such experiment again multiple. Third time reaction anthanium chloride amount was 15 gram and suppose.
    Every temperature was 10°C. Write the obtained data in notebook every step. Now you have to arrange the obtained data properly and analyze that data. The data is shown in 1.03 table.
    In the case of analyzing the obtained data, first in the first anthanium dissolved how much dissolved and temperature decreases that much. From this you can make decision. Like, as anthanium chloride dissolves temperature decreases, so forward anthanium chloride dissolved form has to be measured. The result is that, when anthanium chloride dissolves, water temperature decreases. As conclusion you can say following all this data.
    Always search the research or for research all time ways research has to be searched.
    In chemistry laboratory in use and in laboratory used various chemical substances use caution is needed (Safety Measures in Chemistry Laboratory and in Use of Chemicals)
    Here various kinds of experiments and research are done that laboratory or research lab (Laboratory) is called. One another chemistry laboratory (Chemistry Laboratory) in which for various works of chemistry various materials are kept. In which for various works of chemistry prepared chemical substances use proper application and safety rules have to be followed.
    Small spot (easily catches fire), some damage our bodys nerves again some damage the environment. The substance or gas used in chemistry laboratory most of them are harmful chemical made. So before entering this chemistry laboratory remember to use every substance with caution till big. If inexperienced, any kind of fatal accident can happen. Like — if acid falls your body creates heat. If falls on clothes your clothes can also be damaged. For this in chemistry laboratory appropriate safety clothes and gloves-hat have to be worn. So to protect from body damage like safety clothes and apron (apron) arrange for use in chemistry research lab. For your hand dirt special some gloves or hand socks it is white color soft cloth like gloves. Eye protection is done in hard some safety measure.
    Before using any chemical substance suddenly for injury have to take that chemical shock what process? Is it explosive type combustible or radioactive? For any bottle chemical lab bottle or box label one type scientific right is used. In this regard one new rule (Globally Harmonized System) tag's various signals front from has released element's environment and invention in multiple signal's specific is. This signal's various reading risk and risk level to indicate signal's scientific right is determined.
    Below picture's some scientific right and symbolic signs side its possible risk, risk level and signal's meaning indicating is shown.
    
    Explosive substance: This type of substance can easily explode in specific situation. It can emit a lot of energy, which can be dangerous for surrounding people and things. For example, TNT, dynamite, and nitroglycerin.
    Combustible substance: These substances can easily burn in contact with open fire or in specific situation. Have to be careful when using this type of substance. For example, petrol, ethanol and diesel.
    Toxic substance: Toxic substance if enters body, if goes with breath or if contacts skin can be harmful and can create serious health risk, even death can happen. Among them are benzene, carbon monoxide and insecticide; when using this type of substance personal protection equipment (PPE) is needed.
    Irritant substance: This type of substance not too toxic but can create burning in skin, eyes and respiratory system. Common example as cleaning agent, acid and alkali. When using irritant substance proper protection equipment have to be worn.
    Health risk substance: This type of substance from repeated use can damage specific organ or physical activity of body and can increase health problem risk in long term. Like for lungs or liver harmful substance case caution is needed.
    Radioactive substance: Radiation emitted from radioactive substance can damage cells of human body. It can create deadly health problem. For example, uranium, radium and other radioactive substances, which when using protection equipment wearing is needed.
    Dangerous for environment: This type of substance harmful for environment and can have deadly effect on aquatic and terrestrial biodiversity. These can cause pollution and long-lasting environmental damage. When using and disposing this type of substance proper method have to be followed.
    Corrosive substance: This type of substance can have harmful effect on skin and other materials. It can create burn or deadly damage. For example, strong acid and alkali; when using corrosive substance proper protection equipment have to be used.`,
    };
    
    export default chemistry