import localFont from "next/font/local";
import response from "./server";
import "./globals.css";
import colors from "./colors/colors";
import Nav from "@/components/Nav";
import MobileNav from "@/components/MobileNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${colors.bg} overflow-hidden h-screen w-screen`}>
      <div className="w-full h-[10%] overflow-hidden relative">
          <Nav />
        </div>
        <div className="w-full sm:h-0 sm:w-0 h-[10%] opacity-100 sm:opacity-0 relative">
          <MobileNav />
        </div>
        <div className="w-full sm:h-[90%] h-[70%] overflow-hidden relative">
          {children}
        </div>
        <div className="w-full sm:h-0 sm:w-0 border-[#222222] text-[#111111] text-[11px] flex justify-center items-center border-t-[1px] h-[10%] opacity-100 sm:opacity-0 relative">
          
        </div>
      </body>
    </html>
  );
}
